"""add reparacion_gastos table

Revision ID: 00069dbad98b
Revises: 7d0bddf01669
Create Date: 2025-12-08 18:48:26.723575
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '00069dbad98b'
down_revision = '7d0bddf01669'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparacion_gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reparacion_id'], ['reparacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparacion_gasto')
    # ### end Alembic commands ###