"""init schema

Revision ID: 628b5fe68e5d
Revises: 
Create Date: 2025-10-20 01:00:31.674642
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628b5fe68e5d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###