"""add_adjuntos_incidencia_equipo

Revision ID: 6bbbfa3e9e23
Revises: b076903358e5
Create Date: 2025-11-26 16:54:34.372370
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6bbbfa3e9e23'
down_revision = 'b076903358e5'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo_adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia_adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia_adjunto')
    op.drop_table('equipo_adjunto')
    # ### end Alembic commands ###