"""reparacion: FK equipo ON DELETE CASCADE

Revision ID: 7074faab4b5b
Revises: d27726981169
Create Date: 2025-10-25 23:24:59.788014
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7074faab4b5b'
down_revision = 'd27726981169'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reparacion_equipo_id_fkey'), 'reparacion', type_='foreignkey')
    op.create_foreign_key(None, 'reparacion', 'equipo', ['equipo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reparacion', type_='foreignkey')
    op.create_foreign_key(op.f('reparacion_equipo_id_fkey'), 'reparacion', 'equipo', ['equipo_id'], ['id'])
    # ### end Alembic commands ###