"""add_notas_and_user_fields

Revision ID: 7d0bddf01669
Revises: 886e039c7746
Create Date: 2025-11-27 09:28:33.412396
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7d0bddf01669'
down_revision = '886e039c7746'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###