"""add_user_name_surname

Revision ID: 886e039c7746
Revises: ed0f7af28954
Create Date: 2025-11-26 22:16:28.668174
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '886e039c7746'
down_revision = 'ed0f7af28954'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nombre', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('apellidos', sa.String(length=150), nullable=True))
    op.drop_column('usuario', 'display_name')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'apellidos')
    op.drop_column('usuario', 'nombre')
    # ### end Alembic commands ###