"""usuario unique + checks

Revision ID: 91c8bf68af41
Revises: c4f2d05cea17
Create Date: 2025-10-25 23:58:25.757326
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91c8bf68af41'
down_revision = 'c4f2d05cea17'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('usuario', 'username',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.create_index(op.f('ix_usuario_active'), 'usuario', ['active'], unique=False)
    op.create_index(op.f('ix_usuario_role'), 'usuario', ['role'], unique=False)
    op.create_unique_constraint(None, 'usuario', ['username'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_role'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_active'), table_name='usuario')
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.alter_column('usuario', 'username',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('usuario', 'created_at')
    # ### end Alembic commands ###