"""equipo: fks ondelete set null & types

Revision ID: a53f45ec0ebf
Revises: ed60ed7d5bf6
Create Date: 2025-10-25 22:49:21.791644
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a53f45ec0ebf'
down_revision = 'ed60ed7d5bf6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###