"""usuario: citext email unique + mfa/bloqueos/auditoria

Revision ID: adc6fbc7ed40
Revises: c1b044594b18
Create Date: 2025-10-27 01:00:20.715958
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adc6fbc7ed40'
down_revision = 'c1b044594b18'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', postgresql.CITEXT(), nullable=True))
    op.add_column('usuario', sa.Column('display_name', sa.String(length=120), nullable=True))
    op.add_column('usuario', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('usuario', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('usuario', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usuario', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuario', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('usuario', 'active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_usuario_active'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_role'), table_name='usuario')
    op.create_index('ix_usuario_created_at', 'usuario', ['created_at'], unique=False)
    op.create_index('ix_usuario_last_login_at', 'usuario', ['last_login_at'], unique=False)
    op.create_index('ix_usuario_role_active', 'usuario', ['role', 'active'], unique=False)
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index('ix_usuario_role_active', table_name='usuario')
    op.drop_index('ix_usuario_last_login_at', table_name='usuario')
    op.drop_index('ix_usuario_created_at', table_name='usuario')
    op.create_index(op.f('ix_usuario_role'), 'usuario', ['role'], unique=False)
    op.create_index(op.f('ix_usuario_active'), 'usuario', ['active'], unique=False)
    op.alter_column('usuario', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('usuario', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('usuario', 'password_changed_at')
    op.drop_column('usuario', 'last_login_at')
    op.drop_column('usuario', 'updated_at')
    op.drop_column('usuario', 'locked_until')
    op.drop_column('usuario', 'failed_login_count')
    op.drop_column('usuario', 'totp_secret')
    op.drop_column('usuario', 'mfa_enabled')
    op.drop_column('usuario', 'display_name')
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###