"""initial_clean_schema

Revision ID: b076903358e5
Revises: 
Create Date: 2025-11-23 19:03:12.366119
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b076903358e5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', postgresql.CITEXT(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('ADMIN','MANTENIMIENTO','OPERARIO')", name='ck_usuario_role'),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_usuario_failed_login_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_usuario_created_at', 'usuario', ['created_at'], unique=False)
    op.create_index('ix_usuario_last_login_at', 'usuario', ['last_login_at'], unique=False)
    op.create_index('ix_usuario_role_active', 'usuario', ['role', 'active'], unique=False)
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), server_default='OTRO', nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo in ('ALMACEN','LABORATORIO','TECNICO','OTRO')", name='ck_ubicacion_tipo'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion_id', 'nombre', name='uq_ubicacion_seccion_nombre'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index('ix_ubicacion_nombre', 'ubicacion', ['nombre'], unique=False)
    op.create_index('ix_ubicacion_seccion', 'ubicacion', ['seccion_id'], unique=False)
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identidad', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('nfc_tag', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado in ('OPERATIVO','MANTENIMIENTO','BAJA','CALIBRACION','RESERVA')", name='ck_equipo_estado'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipo_estado', 'equipo', ['estado'], unique=False)
    op.create_index('ix_equipo_estado_tipo', 'equipo', ['estado', 'tipo'], unique=False)
    op.create_index('ix_equipo_identidad', 'equipo', ['identidad'], unique=False)
    op.create_index('ix_equipo_nfc_tag', 'equipo', ['nfc_tag'], unique=False)
    op.create_index('ix_equipo_seccion_id', 'equipo', ['seccion_id'], unique=False)
    op.create_index('ix_equipo_tipo', 'equipo', ['tipo'], unique=False)
    op.create_index('ix_equipo_ubicacion_id', 'equipo', ['ubicacion_id'], unique=False)
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrada_por_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_modificador_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado in ('ABIERTA','EN_PROGRESO','CERRADA')", name='ck_incidencia_estado'),
    sa.ForeignKeyConstraint(['cerrada_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_modificador_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidencia_equipo_estado_fecha', 'incidencia', ['equipo_id', 'estado', 'fecha'], unique=False)
    op.create_index('ix_incidencia_equipo_fecha', 'incidencia', ['equipo_id', 'fecha'], unique=False)
    op.create_index('ix_incidencia_estado_fecha', 'incidencia', ['estado', 'fecha'], unique=False)
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('desde_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('hacia_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['desde_ubicacion_id'], ['ubicacion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hacia_ubicacion_id'], ['ubicacion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimiento_desde_ubicacion_id', 'movimiento', ['desde_ubicacion_id'], unique=False)
    op.create_index('ix_movimiento_equipo_fecha', 'movimiento', ['equipo_id', 'fecha'], unique=False)
    op.create_index('ix_movimiento_fecha', 'movimiento', ['fecha'], unique=False)
    op.create_index('ix_movimiento_hacia_ubicacion_id', 'movimiento', ['hacia_ubicacion_id'], unique=False)
    op.create_table('reparacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('coste_materiales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coste_mano_obra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coste_otros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), server_default='EUR', nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('factura_archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('factura_archivo_path', sa.String(length=500), nullable=True),
    sa.Column('factura_content_type', sa.String(length=100), nullable=True),
    sa.Column('factura_tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_modificador_id', sa.Integer(), nullable=True),
    sa.Column('cerrada_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("estado in ('ABIERTA','EN_PROGRESO','CERRADA')", name='ck_reparacion_estado'),
    sa.ForeignKeyConstraint(['cerrada_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencia.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_modificador_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id', 'incidencia_id', name='uq_reparacion_equipo_incidencia')
    )
    op.create_index('ix_reparacion_equipo_fecha_inicio', 'reparacion', ['equipo_id', 'fecha_inicio'], unique=False)
    op.create_index('ix_reparacion_estado_fecha_inicio', 'reparacion', ['estado', 'fecha_inicio'], unique=False)
    op.create_index('ix_reparacion_incidencia', 'reparacion', ['incidencia_id'], unique=False)
    op.create_table('reparacion_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('path_relativo', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('subido_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reparacion_id'], ['reparacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repfact_reparacion', 'reparacion_factura', ['reparacion_id'], unique=False)
    op.create_index('ix_repfact_subido_en', 'reparacion_factura', ['subido_en'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repfact_subido_en', table_name='reparacion_factura')
    op.drop_index('ix_repfact_reparacion', table_name='reparacion_factura')
    op.drop_table('reparacion_factura')
    op.drop_index('ix_reparacion_incidencia', table_name='reparacion')
    op.drop_index('ix_reparacion_estado_fecha_inicio', table_name='reparacion')
    op.drop_index('ix_reparacion_equipo_fecha_inicio', table_name='reparacion')
    op.drop_table('reparacion')
    op.drop_index('ix_movimiento_hacia_ubicacion_id', table_name='movimiento')
    op.drop_index('ix_movimiento_fecha', table_name='movimiento')
    op.drop_index('ix_movimiento_equipo_fecha', table_name='movimiento')
    op.drop_index('ix_movimiento_desde_ubicacion_id', table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_index('ix_incidencia_estado_fecha', table_name='incidencia')
    op.drop_index('ix_incidencia_equipo_fecha', table_name='incidencia')
    op.drop_index('ix_incidencia_equipo_estado_fecha', table_name='incidencia')
    op.drop_table('incidencia')
    op.drop_index('ix_equipo_ubicacion_id', table_name='equipo')
    op.drop_index('ix_equipo_tipo', table_name='equipo')
    op.drop_index('ix_equipo_seccion_id', table_name='equipo')
    op.drop_index('ix_equipo_nfc_tag', table_name='equipo')
    op.drop_index('ix_equipo_identidad', table_name='equipo')
    op.drop_index('ix_equipo_estado_tipo', table_name='equipo')
    op.drop_index('ix_equipo_estado', table_name='equipo')
    op.drop_table('equipo')
    op.drop_index('ix_ubicacion_seccion', table_name='ubicacion')
    op.drop_index('ix_ubicacion_nombre', table_name='ubicacion')
    op.drop_table('ubicacion')
    op.drop_index('ix_usuario_role_active', table_name='usuario')
    op.drop_index('ix_usuario_last_login_at', table_name='usuario')
    op.drop_index('ix_usuario_created_at', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('seccion')
    # ### end Alembic commands ###