"""reparacion

Revision ID: c4f2d05cea17
Revises: 7074faab4b5b
Create Date: 2025-10-25 23:53:42.395253
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4f2d05cea17'
down_revision = '7074faab4b5b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seccion_nombre'), table_name='seccion')
    op.create_unique_constraint(None, 'seccion', ['nombre'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seccion', type_='unique')
    op.create_index(op.f('ix_seccion_nombre'), 'seccion', ['nombre'], unique=True)
    # ### end Alembic commands ###