"""movimiento: FKs CASCADE/SET NULL

Revision ID: d27726981169
Revises: 5e978b7f82b3
Create Date: 2025-10-25 23:21:28.363470
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd27726981169'
down_revision = '5e978b7f82b3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movimiento_equipo_id_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_hacia_ubicacion_id_fkey'), 'movimiento', type_='foreignkey')
    op.drop_constraint(op.f('movimiento_desde_ubicacion_id_fkey'), 'movimiento', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento', 'equipo', ['equipo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movimiento', 'ubicacion', ['hacia_ubicacion_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'movimiento', 'ubicacion', ['desde_ubicacion_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.drop_constraint(None, 'movimiento', type_='foreignkey')
    op.create_foreign_key(op.f('movimiento_desde_ubicacion_id_fkey'), 'movimiento', 'ubicacion', ['desde_ubicacion_id'], ['id'])
    op.create_foreign_key(op.f('movimiento_hacia_ubicacion_id_fkey'), 'movimiento', 'ubicacion', ['hacia_ubicacion_id'], ['id'])
    op.create_foreign_key(op.f('movimiento_equipo_id_fkey'), 'movimiento', 'equipo', ['equipo_id'], ['id'])
    # ### end Alembic commands ###