"""add_equipo_notas

Revision ID: ed0f7af28954
Revises: 6bbbfa3e9e23
Create Date: 2025-11-26 19:49:57.042273
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed0f7af28954'
down_revision = '6bbbfa3e9e23'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipo', sa.Column('notas', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipo', 'notas')
    # ### end Alembic commands ###