"""fix: index via Column in FKs

Revision ID: ed60ed7d5bf6
Revises: d38a1a881416
Create Date: 2025-10-25 21:48:22.218308
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed60ed7d5bf6'
down_revision = 'd38a1a881416'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('equipo_ubicacion_id_fkey'), 'equipo', type_='foreignkey')
    op.create_foreign_key(None, 'equipo', 'ubicacion', ['ubicacion_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_incidencia_estado'), 'incidencia', ['estado'], unique=False)
    op.create_index(op.f('ix_incidencia_fecha'), 'incidencia', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimiento_fecha'), 'movimiento', ['fecha'], unique=False)
    op.add_column('reparacion', sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('reparacion', sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.alter_column('reparacion', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)
    op.alter_column('reparacion', 'coste',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_reparacion_estado'), 'reparacion', ['estado'], unique=False)
    op.create_index(op.f('ix_reparacion_fecha_inicio'), 'reparacion', ['fecha_inicio'], unique=False)
    op.drop_constraint(op.f('uq_seccion_nombre'), 'seccion', type_='unique')
    op.drop_index(op.f('ix_seccion_nombre'), table_name='seccion')
    op.create_index(op.f('ix_seccion_nombre'), 'seccion', ['nombre'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seccion_nombre'), table_name='seccion')
    op.create_index(op.f('ix_seccion_nombre'), 'seccion', ['nombre'], unique=False)
    op.create_unique_constraint(op.f('uq_seccion_nombre'), 'seccion', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_reparacion_fecha_inicio'), table_name='reparacion')
    op.drop_index(op.f('ix_reparacion_estado'), table_name='reparacion')
    op.alter_column('reparacion', 'coste',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('reparacion', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('reparacion', 'estado')
    op.drop_column('reparacion', 'titulo')
    op.drop_index(op.f('ix_movimiento_fecha'), table_name='movimiento')
    op.drop_index(op.f('ix_incidencia_fecha'), table_name='incidencia')
    op.drop_index(op.f('ix_incidencia_estado'), table_name='incidencia')
    op.drop_constraint(None, 'equipo', type_='foreignkey')
    op.create_foreign_key(op.f('equipo_ubicacion_id_fkey'), 'equipo', 'ubicacion', ['ubicacion_id'], ['id'])
    # ### end Alembic commands ###